name: Terraform fmt & validate check

on:
  pull_request:
    branches:
      - main
      - master

permissions:
  id-token: write
  contents: read

jobs:
  terraform_fmt_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform fmt check
        run: terraform fmt -check -recursive infrastructure/

  terraform_validation:
    runs-on: ubuntu-latest
    needs: terraform_fmt_check
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform init & validate
        working-directory: infrastructure
        run: |
          terraform init
          terraform validate